#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Apache Toree build

on:
  pull_request:
  push:
  schedule:
    # once a day at 6 am (UTC)
    - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      # test specific envs
      COURSIER_NO_TERM: 1
      TOREE_RESOLUTION_VERBOSITY: 0
      TEST_DILATION: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: true
    - name: Checkout
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Add SBT launcher
      run: |
        mkdir -p $HOME/.sbt/launchers/1.3.12
        curl -L -o $HOME/.sbt/launchers/1.3.12/sbt-launch.jar https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.12/sbt-launch.jar
    - name: Build
      run: |
        make clean release
    - name: Run tests
      run: |
        make test
#    See https://issues.apache.org/jira/browse/TOREE-526
#    - name: Run system tests
#      run: |
#        make system-test
    - name: Run license eudit
      run: |
        make audit-licenses
